### PR TITLE
Maximize code coverage

### PR DESCRIPTION
**Pull request by simonmoesorensen**
Added some more coverage of our stuff and did some syntactic sugar on methods

### CODE REVIEW

**Comment by aimas-lund** [comment]
We have a little conflict with this pull request. Could you change your test names to TestDepartment.java instead of DepartmentTests.java (and do the same with hospital).
The reason for this change, is because appearently, Maven auto-detects files in test/java with a "Test" prefix.

**Comment by simonmoesorensen** [comment]
> We have a little conflict with this pull request. Could you change your test names to TestDepartment.java instead of DepartmentTests.java (and do the same with hospital).
> The reason for this change, is because appearently, Maven auto-detects files in test/java with a "Test" prefix.

Can we change them to DepartmentTest.java? I did some google searching and found out that prefixes with 'Test' also works

**Comment by aimas-lund** [comment]
Perhaps. Either way, the suffix is "Tests", so I guess it still will have a hard time, and I took the freedom to change it to TestDepartment.java already.

**Comment by aimas-lund** [comment]
And I think we should go for consistency, yeah?

**Comment by simonmoesorensen** [comment]
So it's a go on the *Test namings and not the Test* one?

**Pull request merged**
